Sync: Return unmodified USX if no chapter deltas
- We had some crashes in production with error

System.IndexOutOfRangeException: Index was outside the bounds of the
array.
   at SIL.XForge.Scripture.Services.DeltaUsxMapper.ToUsx

- Handle cases where we have chapters in USX that are not represented
in chapterDeltas. This may represent a situation with corrupt data in
the SF DB.

Sync: Log the mismatch chapter situation

- Because this may be a situation with inconsistent or corrupt SF DB
data, rather than just silently handle it and move on, alert that it
was detected to aid in any needed investigation.

Give more information in additional error cases

- The same exception can be triggered in other ways as well. But the
error message doesn't give us much information to understand what
might have brought about the problem. Output more information to
assist any follow-up investigation, or if the main fix in this PR
isn't handling the actual problem.
- Re-throw after catching the additional causes of exceptions here
rather than returning oldUsxDoc to avoid overwriting data or
increasing a project's corrupt state.

Report handled problem to bugsnag

- So it shows up in bugsnag if there is still something in SF causing
this problem to recur.
- Also changed the unhandled problem case to combine the diagnostic
message with the exception and throw them together.
- Add test that unhandled problem case gives diagnostics.