SF-743 Don't try to delete nonexistent chapter textdoc
* If the PT cloud is missing some chapters, and SF DB is missing some
textdocs for those chapters, yet SF DB has a projectdoc that knows
those chapters should/can exist, sync can crash with
Microsoft.AspNetCore.NodeServices.HostingModels
.NodeInvocationException: Document does not exist
* Fix by omitting the request for deletion of chapter textdocs that
are not in the SF DB.

Unit tests
* Add test to specify behaviour during the situation in question.
* The call to DeleteAsync fails in production with a
NodeInvocationException. Modify the MemoryRepository to crash in the
same way to assist in writing a test.
* Note that excepting in MemoryRepository in this way also made tests
SyncAsync_DbAndCloudMissingChapter and
ChangeDbToNewSnapshotAsync_Works begin to fail, without this change's
fix. The new test may be less significant then, though it does very
specifically define the situation.