SF-743 Don't try to delete nonexistent chapter textdoc
* If the PT cloud is missing some chapters, and SF DB is missing some
textdocs for those chapters, yet SF DB has a projectdoc that knows
those chapters should/can exist, sync can crash with
Microsoft.AspNetCore.NodeServices.HostingModels
.NodeInvocationException: Document does not exist
* Fix by omitting the request for deletion of chapter textdocs that
are not in the SF DB.

Unit tests
* Add test to specify behaviour during the situation in question.
* The call to DeleteAsync fails in production with a
NodeInvocationException. Modify the MemoryRepository to crash in the
same way to assist in writing a test.
* Note that excepting in MemoryRepository in this way also made tests
SyncAsync_DbAndCloudMissingChapter and
ChangeDbToNewSnapshotAsync_Works begin to fail, without this change's
fix. The new test may be less significant then, though it does very
specifically define the situation.
* SFMemoryRealtimeService:
- Making MemoryRepository.DeleteAsync mimic production by crashing
made test SFProjectServiceTests.DeleteAsync fail. The method being
tested was calling projectDoc.DeleteAsync() and then
RealtimeService.DeleteProjectAsync(projectId), which was crashing
because of how SFMemoryRealtimeService.DeleteProjectAsync is
implemented.
- Testing RealtimeService.DeleteProjectAsync in production shows that
it does not crash in this way.
- So RealtimeService.DeleteProjectAsync was modified to not crash to
be consistent with the behaviour in production. This starts to make
the Memory-based DB for tests more of a tangle, at the expense of
mimicing the in-production behaviour.