use jasmine spyOn instead of ts-mockito spy for questionDoc
simply doing `spy(await env.getQuestionDoc('q6Id'))` with ts-mockito
spy results in later errors:

>       Error: Uncaught (in promise): TypeError: Cannot read
properties of undefined (reading 'get')
>       TypeError: Cannot read properties of undefined (reading 'get')
>           at Spy.getEmptyMethodStub
(node_modules/ts-mockito/lib/Spy.js:41:48)

Perhaps more awaiting needed to happen first for something to be
populated. Not being able to pin it down, there was instead success in
moving to jasmine spyOn.